# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directory: "/api/frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
