# Use an official Node.js runtime as a parent image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
# This ensures that we only re-run npm install if these files change
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy the rest of the application's source code from the host to the container
COPY . .

# Make port 5173 available to the world outside this container (Vite's default port)
EXPOSE 5173

# The command to run when the container starts is specified in docker-compose.yml
# This will be ["npm", "run", "dev", "--", "--host"] 